ENT-10629: Migrate from PCRE to PCRE2
NorthernTechHQ/libntech pull request #199
Opened 2023-12-04 12:33 UTC by vpodzime

2023-12-04 14:15 UTC, craigcomstock approved these changes
cool, looks good to me.

2023-12-04 15:33 UTC, larsewi requested changes
Nice, work 🚀  Just a few things

2023-12-04 15:33 UTC, larsewi commented on libutils/regex.c
> +             * - followed by the name of the named group, NUL-terminated.
```suggestion
             * - followed by the name of the named group, NULL-terminated.
```

2023-12-04 16:29 UTC, vpodzime commented on libutils/buffer.c
> +            break;
Yup! The `assert()` is good because it's debug-only. Plus I guess there should be a warning logged.

2023-12-04 16:31 UTC, vpodzime commented on libutils/buffer.c
> +            result = xrealloc(result, out_size);
`out_size` is adapted by `pcre2_substitute()` thanks to `PCRE2_SUBSTITUTE_OVERFLOW_LENGTH`.

2023-12-04 16:42 UTC, larsewi commented on libutils/buffer.c
> +            result = xrealloc(result, out_size);
Ah, okey. Makes sense 👍

2023-12-05 12:53 UTC, larsewi submitted a review, later dismissed

2023-12-05 13:38 UTC, larsewi approved these changes

2023-12-05 13:39 UTC, merged